oregon_measures/views/admin.py
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash, abort,
    jsonify
)

from flask_login import login_required

from oregon_measures.models.measure import (
    get_measures, get_measure, Measure, MeasureValidationError
)
from oregon_measures.models.county import get_counties
from oregon_measures.forms.admin import MeasureForm

admin = Blueprint(
    'admin', __name__, template_folder='templates',
    url_prefix='/admin'
)


def parse_int(arg):
    """
    Parse values in args as int
    """
    try:
        return int(arg)
    except ValueError:
        abort(404)


@admin.route("/", methods=["GET"])
@login_required
def index():
    """
    Render the admin index
    """
    measure_list = get_measures(request.args)

    return render_template('admin/index.html', measure_list=measure_list)


@admin.route("/measure", methods=["GET", "POST"])
@login_required
def create_measure():
    """
    Endpoint for creating a measure
    :return:
    """
    form = MeasureForm()

    if request.method == 'POST':
        if form.validate():
            form_mod = Measure(
                **{k: v for k, v in form.data.items() if k != 'csrf_token'}
            )
            form_mod.save()
            flash('New Measure created', 'success')

            return redirect(
                url_for('admin.measure_detail', year=form_mod.date.year,
                        number=form_mod.number)
            )

    return render_template('admin/create_measure.html', form=form)


@admin.route("/measure/<year>/<number>/delete", methods=["POST"])
@login_required
def delete_measure(year, number):
    """Delete a measure"""
    year = parse_int(year)
    measure = Measure.find(year, number)

    if measure:
        measure.delete()
        flash('Measure deleted', 'success')
        return redirect('/admin')
    else:
        abort(404)


@admin.route("/measure/<year>/<number>", methods=["GET", "POST"])
@login_required
def measure_detail(year, number):
    """
    Measure detail page and update form.

    This view function displays a view of the current measure
    and supports methods for updating the measure.

    Forms values can be:
        - number (string)
        - date (string)
        - description (string)
        - yes_votes_bulk (string) - new line separated list of votes
        - no_votes_bulk (string) - new line separated list of votes
        - yes_votes (array)
        - no_votes (array)
    """
    year = parse_int(year)
    measure = get_measure(year, number)

    if not measure:
        abort(404)

    counties = measure.get('results') or get_counties()

    measure_mod = Measure(
        number=measure.get('number'), description=measure.get('description'),
        date=measure.get('date'), measure_id=measure.get('id')
    )

    form = MeasureForm(obj=measure_mod)

    if request.method == 'POST':
        if form.validate():
            try:
                measure_mod.update(**form.data)
                measure_mod.update_results(request.form, counties)
                flash('Measure results saved', 'success')

                return redirect(
                    url_for('admin.measure_detail', year=measure_mod.date.year,
                            number=measure_mod.number)
                )

            except MeasureValidationError as exc:
                flash(exc, 'danger')
        else:
            flash('Form errors', 'danger')

    measure_link = url_for('public.measure_detail', measure=measure_mod.number,
                           year=measure_mod.date.year)
    delete_link = url_for('admin.delete_measure', number=measure_mod.number,
                          year=measure_mod.date.year)

    return render_template('admin/measure.html', form=form,
                           measure_link=measure_link, delete_link=delete_link,
                           measure=measure, counties=counties)


@admin.route("/api/measure/<year>/<number>", methods=["GET", "POST"])
def measure_detail_api(year, number):
    """
    API endpoint for updating a measure
    """
    year = parse_int(year)
    measure = Measure.find(year, number)
    counties = get_counties()

    print(request.form)
    if not measure:
        abort(404)

    if request.method == 'POST':
        try:
            measure.update(**request.form)
            measure.update_results(request.form, counties)
        except MeasureValidationError as exc:
            abort(400, exc)

    return jsonify(measure.json())

oregon_measures/views/auth.py
from oregon_measures.app import login_manager, flask_bcrypt
from flask import (
    Blueprint, render_template, request,
    flash, redirect
)
from flask_login import (
    login_required, login_user,
    logout_user
)

from oregon_measures.models.auth import User

auth = Blueprint(
    'auth', __name__, template_folder='templates'
)


@auth.route("/login", methods=["get", "post"])
def login():
    if request.method == "POST" and "email" in request.form:
        email = request.form["email"]
        user = User.find_user(email)

        if user:
            valid_creds = flask_bcrypt.check_password_hash(
                user.password, request.form["password"]
            )

            if valid_creds:
                remember = request.form.get("remember", "no") == "yes"

                if login_user(user, remember=remember):
                    return redirect('/admin')

        flash("unable to log you in")

    return render_template("/auth/login.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out.", 'success')
    return redirect('/login')


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect('/login')


@login_manager.user_loader
def load_user(user_id):
    if user_id is None:
        redirect('/login')

    user = User.find_user(user_id)

    return user

oregon_measures/views/public.py
from flask import (
    Blueprint, render_template, jsonify, abort, request
)

from oregon_measures import settings
from oregon_measures.app import get_db
from oregon_measures.models.measure import (
    get_measures, get_measure
)

public = Blueprint(
    'public', __name__, template_folder='../templates'
)


@public.route('/', methods=["GET"])
def index():
    """
    Render the public site index
    """
    return render_template('index.html')


@public.route('/measure/<year>/<measure>')
def measure_detail(year, measure):
    """
    Render the detail page for a measure
    """
    return render_template('index.html')


@public.route('/api/measure', methods=['GET'])
def measures():
    """
    Endpoint for searching measures
    """
    measure_list = get_measures(request.args)

    return jsonify(measure_list)


@public.route('/api/measure/<year>/<number>', methods=['GET'])
def measures_detail(year, number):
    """
    Endpoint for searching measures
    """
    try:
        year = int(year)
    except ValueError:
        return abort(400, 'Invalid input provided')

    meas = get_measure(year, number)

    if meas:
        return jsonify(meas)

    abort(404)


@public.route('/api/measure/years', methods=['GET'])
def measure_years():
    """
    Returns the years for which we have measures
    """
    db = get_db()
    cursor = db.cursor()

    query = """
        SELECT DISTINCT EXTRACT(year FROM date) 
        FROM measure
        ORDER BY EXTRACT(year FROM date) DESC
    """
    cursor.execute(query)

    return jsonify(
        [r[0] for r in cursor.fetchall()]
    )


@public.context_processor
def constants_processor():
    return {
        'API_URL': settings.API_URL
    }

oregon_measures/templates/forum.html
{% extends 'layout.html' %}


{% block main %}
   <h2>ITP DWD Forum</h2>
   <div>
      <a class="moot" href="https://moot.it/i/itpdwd">itpdwd forums</a>
   </div>

{% endblock %}


{% block head %}
   {{ super() }}
   <!-- (1) Optimize for mobile versions: http://goo.gl/EOpFl -->
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <!-- (1) force latest IE rendering engine: http://goo.gl/tf4JH -->
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

   <!-- (1) Moot look and feel -->
   <link rel="stylesheet" href="https://cdn.moot.it/1/moot.css">

   <!-- (4) Custom CSS -->
   <style>
   body {
      font-family: "myriad pro", tahoma, verdana, arial, sans-serif;
      margin: 0; padding: 0;
   }

   .moot {
      font-size: 18px;
   }
   </style>
{% endblock %}

{% block scripts %}
   {{ super() }}
   <!-- (1) Moot client application -->
   <script src="https://cdn.moot.it/1/moot.min.js"></script>
{% endblock %}

oregon_measures/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <title>Oregon Ballot Measures</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Open+Sans" rel="stylesheet">

    <!-- GA -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-97391921-2', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body>
  <div id="app"></div>

  <!-- Define global config object -->
  <script>
    window.oregonMeasureApp = {
      'geoJson': '{{ url_for('static', filename='json/geo.json') }}',
      'measuresJson': '{{ url_for('static', filename='json/measures.json') }}',
      'apiUrl': '{{ API_URL }}'
    };
  </script>

  <!-- Attach React components -->
  <script type="text/javascript" src="{{ url_for('static', filename='bundle.js') }}"></script>
</body>

oregon_measures/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Oregon Measures</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0-rc2/css/bootstrap.min.css">

    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
        <ul class="nav nav-pills">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
            <li><a href="{{ url_for('public.index') }}">Public Site</a></li>
            <li><a href="{{ url_for('admin.create_measure') }}">Create Measure</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% endif %}
        </ul>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert"
                      aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
                {{ message }}
            </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block main %}{% endblock %}
    </div> <!-- /container -->

    {% block scripts %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0-rc2/js/bootstrap.min.js"></script>
    {% endblock %}
    {% block extra_scripts %}{% endblock %}
</body>
</html>

oregon_measures/templates/note_display.html
{% extends "layout.html" %}

{% block main %}
<div class="page-header">
	<h1>{{note.title}}</h1>
	{% if current_user.id == note.user.id%}
    <p><a href="/notes/{{note.id}}/edit"><span class="label label-info">edit</span></a></p>
    {% endif %}
	
</div>

<div class="row">
	
	<div class="col-md-10">
		
		<div id="notes">
			{{ note.content }}
		</div>
		
	</div>
</div>
{% endblock %}

{% block styles %}{% endblock %}
{% block scripts %}{% endblock %}

oregon_measures/templates/note_edit.html
{% extends "layout.html" %}


{% block main %}
<div class="row">

	<div class="col-md-9">
		
		{% with messages = get_flashed_messages() %}
		  {% if messages %}
		    <ul class=flashes>
		    {% for message in messages %}
		    <span class="label label-success">{{message}}</span>
		    {% endfor %}
		    </ul>
		  {% endif %}
		{% endwith %}
		<form method="POST" action="" id="admin_note_edit" class="well form-horizontal">
			<fieldset>
          		<legend>
          			{{title}}
          			{% if note %}
          			<a href="/notes/{{note.id}}">view note</a>
          			{% endif %}

          		</legend>
				<div class="control-group">
					<label class="control-label" for="title">Title</label>
					<div class="controls">
					  <input type="text" class="span7 input-xlarge" name="title" id="title" value="{{note.title}}">
					  <p class="hide help-block">In addition to freeform text, any HTML5 text-based input appears like so.</p>
					</div>
				</div>

				
		
				<div class="control-group">
					<label class="control-label" for="content">Note</label>
					<div class="controls">
					  <textarea class="span10 input-xlarge" style="resize:both; width: 810px; height: 350px;" name="content" id="content">{{note.content}}</textarea>
					  
					</div>
				</div>
          	</fieldset>

			
			<input type="submit" value="Save note" class="btn btn-primary">
		</form>
	</div>

	
</div>


{% endblock %}

{% block scripts %}{% endblock %}